### DISCUSSION TITLE
Select: [data-state='closed'] conflicts with animations

### DISCUSSION THREAD

**Discussion by Johnhersh** [radix-ui/primitives#2420] [Help]
I'm using the Select component. On <Select.Content> I have a css animation:
```css
    &[data-state='open'] {
        animation: fadeIn 200ms ease-out;
    }
    &[data-state='closed'] {
        animation: fadeOut 200ms ease-in;
    }
```
It works fine for open, but for closed the component gets unmounted before the animation ends
