### DISCUSSION TITLE
Customize arrow for tooltip and popover border

### DISCUSSION THREAD

**Discussion by nandcello** [radix-ui/primitives#868] [Help]
Say I wanna add a black border around the whole tooltip, including the arrow. I tried adding a solid 1px black border like so:
https://codesandbox.io/s/funny-mclaren-ltvsy?file=/App.js

but it also has a line underneath the triangle. How do I get rid of the line so the border only outlines the tooltip including the arrow?

**Comment by benoitgrelard** [comment]
HI @ninoM,

The main issue with your sandbox is that you're using border on the arrow which is an SVG so it expects stroke rather.
However, getting a seamless solid border around the whole thing is quite tricky but doable.
You could use `filter: drop-shadow` but that's limited as you can't get it quite solid but rather blurry like a shadow.

Here's an old sandbox (not the latest version of primitives) which shows you how you might do it with a custom arrow:
https://codesandbox.io/s/popover-seamless-arrow-qtgf5?file=/src/App.js

Let me know if that helps!

**Reply by sinchang** [reply]
Hi @benoitgrelard,

Thanks for your providing the solution, but still not the best fit for me.

I found a solution developed by [Reakit](https://reakit.io/docs/popover/), it's easy to customize the SVG fill and stroke based on the class name.

![image](https://user-images.githubusercontent.com/3297859/154447628-39cb99b4-5714-438e-945c-99cb8a5d351d.png)
![image](https://user-images.githubusercontent.com/3297859/154447977-ab64f7de-ccea-418b-a6aa-8afacaef11ab.png)

so, Can we adopt this feature into `Radix primitives` as well?

**Reply by benoitgrelard** [reply]
You can use whatever SVG you want, that demo is just an example, so if you find the one from reakit easier to use, you can use that SVG.

**Reply by vnugent** [reply]
Arrow component no longer accepts `as` prop.  Any ideas how to do this in the current version?  Thanks!

**Reply by joaom00** [reply]
@vnugent You can use the `asChild` prop

**Reply by vincerubinetti** [reply]
I ended up using this, since I just wanted a blur/shadow:

```css
.arrow {
  filter: drop-shadow(0 0 3px black);
}

.content[data-side="top"] .arrow {
  clip-path: inset(0 -10px -10px -10px);
}
```

The `clip-path` will probably be useful to people, to cutoff the unsightly-ness at the top here:
<img width="127" alt="Screenshot 2023-11-13 at 3 18 58 PM" src="https://github.com/radix-ui/primitives/assets/8326331/b3c7a18f-481b-4a2e-aba4-25ba3e0b91e6">

**Reply by ADTC** [reply]
Thank you @vincerubinetti I used this for popover arrow:

```scss
.popoverArrow {
  fill: white;
  // Add a shadow behind the arrow to create a 3D effect.
  filter: drop-shadow(0 0 3px gray);
  // Hide the shadow which overlaps the content above the arrow.
  clip-path: inset(0 -10px -10px -10px);
}
```

```tsx
// inside Popover.Content:
<Popover.Arrow className={Styles.popoverArrow} />
```
