### ISSUE TITLE
[New Primitive] `OverflowTracker`

### ISSUE THREAD

**Issue by arturbien** [radix-ui/primitives#2377]
## Feature request

Add new primitive component that allows styling other HTML elements based on it's overflow state.
One popular use case would be indicating to the user that there's more content to be seen in an element that can be panned or scrolled:

https://github.com/radix-ui/primitives/assets/28541613/d9685be5-c052-4758-9de9-4592dbc99c3e

### Overview

Some example UI elements where it would be used:
- scrollable element with lots of text,
- horizontally scrollable navbar,
- element that can be panned in every direction (like a map),
- scrollable dropdown.

### Examples in other libraries

I don't know any other library that implements that

### Who does this impact? Who is this for?

All users

### Additional context

I've made a simple proof of concept of how it could be implemented in this [Codesandbox](https://codesandbox.io/p/sandbox/scroll-indicator-dq9snf).

This implementation is based on [IntersectionObserver API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) so it's really performant, will work with elements that might change their size or content (adding/removing children) over time.

How it works:
- The primitive renders a wrapper element with absolutely positioned "edge" elements - invisible elements for each side (top,right,bottom,left),
- Using IntersectionObserver tracks visibility changes of "edge elements" and sets `data-overflow` attributes on the wrapper element allowing us to style other elements based on those attributes

API:
```jsx
    <OverflowTracker className="scrollable-nav">
      <nav>
        <div>Images</div>
        <div>Videos</div>
        <div>Shopping</div>
        ...
      </nav>
    </OverflowTracker>
```
Then in CSS:
```css
.scrollable-nav {
  width: 100%;
  overflow-x: scroll;

  --fade-length: 40px;
  --start-fade: 0px;
  --end-fade: 0px;
  -webkit-mask: linear-gradient(
    to right,
    transparent,
    black var(--start-fade),
    black calc(100% - var(--end-fade)),
    transparent
  );
}

.scrollable-nav[data-overflow-left] {
  --start-fade: var(--fade-length);
}

.scrollable-nav[data-overflow-right] {
  --end-fade: var(--fade-length);
}
```

We could also add more options to the component like callbacks or `rootMargin` setting.
I am not sure about the name of the component and its attributes, but we can discuss that. 

If you accept this proposal and we agree on the API I am happy to submit a PR. 🤓
